#!/bin/bash

mkdir -p build
pushd build
[ -d elasticsearch-templates ] || git clone https://github.com/ViaQ/elasticsearch-templates
  pushd elasticsearch-templates/templates/foreman/
    make
    cp org.foreman.*{json,asciidoc} ../../../..
  popd
popd
